In [1]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# Load the data into a pandas DataFrame
df = pd.read_csv('consolidatedmh.csv')

df.fillna("", inplace=True)

In [2]:
mapping = {
    "General Discussion / Questions / Support": [
        "Opinion / Thought / Idea / Discussion",
        "Seeking Support",
        "Undiagnosed Questions",
        "Questions/Advice/Support",
        "Seeking Empathy / Support",
        "General Question About BP",
        "General Discussion",
        "Community Discussion",
        "Question",
        "Discussion",
        "User in need of help that I have no relation to",
        "is this actually a problem and if so where do i go to fix it?",
        "is it okay to do this?",
        "is there something seriously wrong with me",
        "what does it mean girl is in love with psychopath/sociopath?",
        "why am i like this?",
        "wtf do i do? ",
        "shame and guilt",
        "should i be worried about my mom?",
        "what is this called??",
        "wtf do i do next???",
        "what does this mean?",
        "how to gett rid of obsession?",
        "dealing with pro-russian voice in my head",
        "am i just messed up or is there hope",
        "anyone relate ?",
        "distorted fantasy",
        "dae",
        "positives",
        "harm reduction",
        "lgbtq+",
    ],
    "Rant / Vent": [
        "Rant / Vent",
        "Vent",
        "VENT / RANT",
        "Vent (comments welcome)",
        "Venting",
        "Rant/Story",
        "Manic Rant",
        "Rant/Discussion",
        "Question/Venting",
        "Question/Need Support",
        "Question/Advice",
        "Venting/needing some help",
        "Venting Post",
        "Therapy Rant",
        "rant",
        "story",
    ],
    "Advice / Encouragement": [
        "Advice / Encouragement",
        "Advice Needed",
        "Advice to Give",
        "Tips/Suggestions",
        "Advice/Support",
        "Happiness &amp; Positivity",
        "Encouragement",
        "Encouragement - Story Time",
        "Input",
        "Perspective Needed",
        "Helpful Tips!",
        "Help",
        "Needs A Hug/Support",
        "Support",
        "Seeking Support &amp; Advice",
        "💭Seeking Support &amp; Advice",
        "obsessions about a person",
    ],
    "Medication / Medical / Treatment": [
        "Medication",
        "Medications",
        "Therapist / Doctors",
        "Vitamin/Supplement",
        "Medical Study",
        "Med Question",
        "Medication Discussion",
        "Question About Meds",
        "Question about Meds",
        "Medical Advice",
        "Medicine",
        "therapy",
    ],
    "Work / School / Relationship / Lifestyle": [
        "Work / School",
        "Relationships",
        "Pro Tip",
        "Food and recipes",
        "Driving",
        "Lifestyle",
        "Travel",
        "Relationship/Love Issues",
        "Family/Friendship Issues",
        "School/Workplace Issues",
        "Health",
        "Work/School",
        "Family/Relationship",
        "Friend/Family",
        "SOS!",
        "Relationships ",
        "Selfie ",
        "Reminder",
        "divorce",
        "loneliness",
        "loss of a loved one",
        "financial issues",
        " self esteem issues",
        "flair",
    ],
"Progress / Positivity / Success": [
    "Progress / Good News ☀️",
    "Success/Celebration",
    "Accountability",
    "Success Story",
    "Small Triumph",
    "Recovery Story",
    "Progress!",
    "Lesson Learned",
    "Positivity",
    "Happy!",
    "Success!",
    "Share Your Victories",
    "💖Positivity &amp; Affirmation Post",
    "🌟Success Story/Small Triumph",
    "Over 30",
    "Uplifting",
    "Anxiety Resource",
    "Sleep",
    "DAE Questions",
    "Progress Post",
    "Good News / Happy",
],
"Art / Media / Entertainment": [
    "Art",
    "Video",
    "Meme",
    "Music",
    "Original Art",
    "Non-Original Art",
    "I Made This!",
    "Humor",
    "Humour",
    "Art/Meme",
    "Infographic",
    "Mortal Danger",
    "Guess the Meds",
],
"Resources / Literature / Research": [
    "Resources",
    "Literature",
    "Research",
    "Scientific Article",
    "Educational Resource",
    "Reference Material",
    "Scientific Research",
    "Peer-Reviewed Study",
    "resource",
    "clinical psychology study",
],
"Mental Health Issues / Symptoms": [
    "Mental Health",
    "Symptoms",
    "Depression",
    "delusions",
    "Anxiety",
    "Mental Health Issue",
    "Mood Disorder",
    "PTSD",
    "OCD",
    "Eating Disorder",
    "ADHD",
    "Borderline Personality Disorder",
    "BPD",
    "hallucinations / delusions",
    "hallucinations",
    "disorganized thoughts",
    "tobacco / alcohol / drugs",
    "obsession sharing!",
    "suicidal thoughts",
    "tactile/auditory hallucinations",
],
"Trigger Warning / Content Warning": [
    "Trigger Warning",
    "Content Warning",
    "TW",
    "CW",
    "mention of suicide",
    "suicide",
    "suicidal",
    "undiagnosed",
    "self harm",
    "undiagnosed, suicide, self-harm and loss of a loved one",
    "dangerous behavior warning",
    "dangerous behavior",
    "nsfw",
],
"Introduction / New Member / Community": [
    "Introduction",
    "New Member",
    "Community",
    "New User",
    "Hello",
    "New Here",
    "New to the Sub",
    "Newbie",
    "First Post",
    "oops, i did it... again",
    "urgent: coping skills needed",
    "baby borderline",
    "new coping skill achievement unlocked!",
    "radical acceptance",
    "quiet borderline",
    "acted opposite to emotion",
    "it's not the end of the world",
    "veteran borderline",
    "💬general post",
    "💬general dbt post",
    "dae?",
],
"Mod Announcement / Official": [
    "Mod Announcement",
    "Official",
    "Admin",
    "Rules",
    "Moderator",
    "mod post",
    "🌿mj 🌿",
    "announcement",
    "guest ama",
    "monthly town hall",
    "meta",
    "drug use",
    "war veterans ",
    "sadness / grief",
    "opinion / thoughts",
    "feelings friday",
    "member poll ",
    "anger issues",
    "test",
    "hospitalization",
    "just sharing",
    "megathread: weekly wins",
    "megathread: short posts",
    "megathread: newly diagnosed",
]
}

In [3]:
def map_flair_to_key_text(flair):
    if pd.isna(flair) or flair == '':
        return "Other"
    flair = flair.lower()
    for key, flair_list in mapping.items():
        for flair_item in flair_list:
            if flair_item.lower() in flair:
                return key
    if "tw" in flair or "cw" in flair:
        return "Trigger Warning / Content Warning"
    if "question" in flair or "advice" in flair:
        return "General Discussion / Questions / Support"
    if "🚶💀" in flair:
        return "General Discussion / Questions / Support"
    if "snoo" in flair:
        return "General Discussion / Questions / Support"
    if "need support" in flair:
        return "General Discussion / Questions / Support"
    return "Other"

In [4]:
for index, data_point in df.iterrows():
    df.at[index, "map_flair"] = map_flair_to_key_text(data_point["Flair"])

In [5]:
# Get all unique values of the 'flair' column
unique_flairs = df['map_flair'].unique().tolist()

# Print the results
print(unique_flairs)

['General Discussion / Questions / Support', 'Rant / Vent', 'Medication / Medical / Treatment', 'Work / School / Relationship / Lifestyle', 'Advice / Encouragement', 'Trigger Warning / Content Warning', 'Mental Health Issues / Symptoms', 'Introduction / New Member / Community', 'Progress / Positivity / Success', 'Art / Media / Entertainment', 'Resources / Literature / Research', 'Mod Announcement / Official', 'Other']


In [6]:
df = df.drop(df[df['map_flair'] == 'specific'].index)

In [7]:
!pip install embedders transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [8]:
# Logistic Regression spits out warnings on large datasets. For now, there warning will be surpressed.
# This warning will get taken care of in a later version
import warnings
warnings.filterwarnings("ignore")

# Basis libraries
import numpy as np
import pandas as pd
import pickle
import sys
import time
from tqdm import tqdm
from datetime import datetime
from configparser import ConfigParser
from pathlib import Path

import torch 
import torch.nn as nn

# Sklearn libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    mean_squared_error,
)

# Embedders and Transformers
from transformers import AutoTokenizer, AutoModel
from embedders.classification.contextual import TransformerSentenceEmbedder

In [9]:
def feature_getter(df):
    """
    Function to grab and validate multiple column names from user.
    Input should be a pandas DataFrame.

    Args:
    df -> An already loaded pandas DataFrame.
    """
    while True:
        try:
            features_input = "Title, Text"
            features_cleaned = [i.strip() for i in features_input.split(sep=",")]
            if pd.Series(features_cleaned).isin(df.columns).all():
                break
            else:
                pass
        except:
            pass
    return features_cleaned

def target_getter(df):
    """
    Function to grab and validate a single column name from user.
    Input should be a pandas DataFrame.

    Args:
    df -> An already loaded pandas DataFrame.
    """
    while True:
        try:
            target_input = "map_flair"
            if target_input in df:
                break
            else:
                pass  
        except:
            pass
    return target_input

In [10]:
# Use cuda if available 
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

# get datetime dd/mm/YY H:M
now = datetime.now()
dt_string = now.strftime("%d-%m-%Y %H-%M")

In [11]:
feature_columns = feature_getter(df)

corpus = df[feature_columns]
if len(corpus.columns) > 1:
    corpus = corpus[corpus.columns].apply(
        lambda x: ",".join(x.dropna().astype(str)), axis=1
    )
    corpus = corpus.tolist()
else:
    corpus = corpus.squeeze().tolist()

In [12]:
# Get the names of the labels
target_column = target_getter(df)
target = df[target_column].values

# Identify if the labels are strings and need encodig
if target.dtype == 'O' or str:
    encoder = LabelEncoder()
    target = encoder.fit_transform(target)
    encoder_usage = True
else:
    encoder_usage = False

In [13]:
model_name = "distilbert-base-uncased"
sent_transformer = TransformerSentenceEmbedder(model_name)
word_embeddings = sent_transformer.transform(corpus)
embeddings = np.array(word_embeddings)

Some weights of the model checkpoint at /root/.cache/torch/sentence_transformers/distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_layer_norm.weight', 'vocab_transform.bias', 'vocab_transform.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Initializing model, might take some time...


Encoding batches ...: 100%|██████████| 1821/1821 [30:06<00:00,  1.01it/s]


In [14]:
# Setting up features and labels
features =  torch.FloatTensor(embeddings).to(device)
target = torch.LongTensor(target).to(device)

# Splitting the data
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

try:
    num_classes = len(encoder.classes_)
except:
    num_classes = len(df[target_column].value_counts())

In [27]:
model = nn.Sequential(
    nn.Linear(X_train.shape[1], 512),
    nn.ReLU(),
    nn.BatchNorm1d(512),
    nn.Dropout(p=0.3),

    nn.Linear(512, 256),
    nn.ReLU(),
    nn.BatchNorm1d(256),
    nn.Dropout(p=0.3),

    nn.Linear(256, 128),
    nn.ReLU(),
    nn.BatchNorm1d(128),
    nn.Dropout(p=0.3),

    nn.Linear(128, 64),
    nn.ReLU(),
    nn.BatchNorm1d(64),
    nn.Dropout(p=0.3),

    nn.Linear(64, num_classes)
).to(device)

loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=0.0005, weight_decay=0.01)

In [28]:
losses = []
print(" ")
print("Training model...")

# Training loop of the model
num_epochs = 5000 
for epoch in range(num_epochs):
    # Create prediction of the model
    y_hat = model(X_train)

    # Calculate loss
    loss = loss_function(y_hat, y_train)
    losses.append(loss.item())

    # Backpropagate to update weights
    model.zero_grad()
    loss.backward()

    #if epoch % 10 == 0:
    sys.stdout.write(f'\rLoss of {round(float(loss), 2)} at epoch {epoch+1} of {num_epochs}')
    sys.stdout.flush()

    optimizer.step()

 
Training model...
Loss of 0.54 at epoch 5000 of 5000

In [29]:
try:
    # Save model
    torch.save(model, "ml/model.pt")

    # Save encoder
    with open("ml/encoder.pkl", "wb") as handle:
        pickle.dump(encoder, handle)

except:
        # Save model
    torch.save(model.state_dict(), "model.pt")

    # Save encoder
    with open("encoder.pkl", "wb") as handle:
        pickle.dump(encoder, handle)

In [31]:
y_pred = []
model.eval()
for i in X_test:
    pred = model(i.unsqueeze(0))
    pred_numpy = pred.cpu().detach().numpy().astype(int)
    y_pred.append(np.argmax(pred_numpy))

# COnvert y_test to a numpy array
y_test = y_test.cpu().numpy()

In [32]:
# Generate evaluation metrics
print(" ")
print("Generating evaluation metrics on unseen testing data...")
print("- - - - - - - - - - - - - - - -")
print(f"Model accuracy is: {round(accuracy_score(y_test, y_pred), 2) * 100} %")
print("- - - - - - - - - - - - - - - -")
print(f"Mean squared error is: {round(np.sqrt(mean_squared_error(y_test, y_pred)), 2)}")
print("- - - - - - - - - - - - - - - -")
print(f"The confusion matrix is:")
for row in confusion_matrix(y_test, y_pred):
    print(row)

 
Generating evaluation metrics on unseen testing data...
- - - - - - - - - - - - - - - -
Model accuracy is: 56.00000000000001 %
- - - - - - - - - - - - - - - -
Mean squared error is: 3.59
- - - - - - - - - - - - - - - -
The confusion matrix is:
[2261   22 1466    5   80    9   17 1258   48  316    5   15   62]
[ 42 155  70   4   2   1  14  91  11  14   3   1  11]
[2114   24 7347   18  159   13   52 1656   86  440    4   15   53]
[ 73   2 150  12   5   1   3  85   4  48   2   1   2]
[254   4 274   0 326   2   9 155   8  16   2   1   6]
[ 70   5 164   4   2  21   3 114   6  29   0   2   6]
[182  22 138   0   8   3  44 312  12  56   2   1   4]
[ 1779    66  1542    11   125    11    72 14830    67   888    17    33
    47]
[163  13 247   5  11   1  12 166 169  55   0   1   9]
[ 691    7  500    7    9    2   17 1400   27  924    1   14   25]
[18  6 25  1  1  0  2 46  5  3 15  1  2]
[132   7 141   2   6   0   6 282   7  83   0  14   3]
[455   7 185   3  15   7   2 273  25  86   0   2 144]